import styles from './layout.css'; // Importa los estilos globales CSS
import Imagen from './components/Image';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      
      <body className={styles.body}>
        <Imagen/>
        {children}
        </body>
    </html>
  );
}
